site_name: Computational Structural Immunology Symposium
site_description: A symposium focused on the intersection of computational methods and structural immunology.
strict: false
site_url: https://csi.github.io

theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep orange
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: deep orange
    accent: indigo
    toggle:
      icon: material/weather-night
      name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.sections
    # - navigation.top
    - search.highlight
    - search.suggest
  icon:
    logo: 'material/library-outline'
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: images/logo.png
  logo: images/logo.png

extra:
  version:
    provider: mike

extra_css:
  - css/extra.css

# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- About: index.md
- Schedule: schedule.md

markdown_extensions:
# https://python-markdown.github.io/extensions/
- toc:
    permalink: true
- admonition
# https://facelessuser.github.io/pymdown-extensions
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    pygments_lang_class: true
- pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.magiclink
- pymdownx.keys
- pymdownx.snippets: # use files outside of docs folder, syntax is `--8<-- "path/to/file"`
    base_path: [.]

watch:
- docs

plugins:
- mike:
    alias_type: symlink
    canonical_version: latest
- search